---
  name: build-ublue-hyprland
  on:
    pull_request:
      branches:
        - main
    schedule:
      - cron: '05 10 * * *'  # 10:05am UTC everyday
    push:
      branches:
        - main
        - develop
      paths-ignore:
        - '**/README.md'
    workflow_dispatch:
  
  jobs:
    build_fedora:
      permissions:
        contents: read
        packages: write
        id-token: write
      name: "Build Fedora"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}-fedora"
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
        hyprland_build: "fedora"
        source_tag: 40
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

    build_solopasha:
      permissions:
        contents: read
        packages: write
        id-token: write
      name: "Build Solopasha"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}-solopasha"  
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
        hyprland_build: "solopasha"
        source_tag: 40
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      
    build_git:
      permissions:
        contents: read
        packages: write
        id-token: write
      name: "Build Git"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}-git"  
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
        hyprland_build: "git"
        source_tag: 40
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    
    build_solopasha_virtualization:
      permissions:
        contents: read
        packages: write
        id-token: write
      name: "Build Solopasha Virtualization"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}-solopasha-virtualization"  
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
        hyprland_build: "solopasha"
        virtualization: "yes"
        source_tag: 40
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    
    build_git_virtualization:
      permissions:
        contents: read
        packages: write
        id-token: write
      name: "Build Git Virtualization"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}-solopasha-virtualization"  
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
        hyprland_build: "git"
        virtualization: "yes"
        source_tag: 40
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
  
    build_fedora_iso:
      name: "Build ISO for Fedora"
      uses: ./.github/workflows/build-iso.yml
      needs: build_fedora
      with:
        image_name: "${{ github.event.repository.name }}-fedora"
        image_repo: "ghcr.io/cjuniorfox"
        image_tag: "latest"
        version: 40
  
    upload_fedora_iso_to_s3:
      name: "Upload Fedora ISO to S3"
      uses: ./.github/workflows/upload-iso-to-s3.yml
      needs: build_fedora_iso
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        s3_bucket: juniorfox-net-isos
        aws_region: sa-east-1
        iso_name: ${{ needs.build_fedora_iso.outputs.iso_name }}
        checksum: ${{ needs.build_fedora_iso.outputs.checksum }}