---
name: "ublue hyprland 40"
on:
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC every day
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: build
    uses: ./.github/workflows/reusable-build-no-git.yml
    secrets: inherit
    with:
      fedora_version: 40
