---
name: build-ublue-hyprland
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build_main:
    name: "Build Main"
    uses: ./.github/workflows/build-and-iso.yml
    with:
      variation: "fedora"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  build_solopasha:
    name: "Build Solopasha"
    uses: ./.github/workflows/build-and-iso.yml
    with:
      variation: "solopasha"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  build_git:
    name: "Build Git"
    uses: ./.github/workflows/build-and-iso.yml
    with:
      variation: "git"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  build_solopasha_virt:
    name: "Build Solopasha with Virtualization"
    uses: ./.github/workflows/build-and-iso.yml
    with:
      variation: "solopasha"
      version: 40
      virtualization: "yes"
    permissions:
      contents: read
      packages: write
      id-token: write

  build_git_virt:
    name: "Build Git with Virtualization"
    uses: ./.github/workflows/build-and-iso.yml
    with:
      variation: "git"
      version: 40
      virtualization: "yes"
    permissions:
      contents: read
      packages: write
      id-token: write