---
  name: build-ublue-hyprland
  on:
    pull_request:
      branches:
        - main
    schedule:
      - cron: '05 10 * * *'  # 10:05am UTC everyday
    push:
      branches:
        - main
        - develop
      paths-ignore:
        - '**/README.md'
    workflow_dispatch:
  
  jobs:
    build_push:
      name: "Build and Push"
      uses: ./.github/workflows/build-push.yml
      with:
        image_name: "${{ github.event.repository.name }}"  
        image_desc: "Hyprland Shell Blue Image"
        image_registry: "ghcr.io/${{ github.repository_owner }}"
      secrets:
        SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      permissions:
        contents: read
        packages: write
        id-token: write
  
    build_iso:
      uses: ./.github/workflows/build-iso.yml
      needs: build_push
  
    upload_iso_to_s3:
      uses: ./.github/workflows/upload-iso-to-s3.yml
      needs: build_iso
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Corrected secret reference
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Corrected secret reference
      with:
        s3_bucket: juniorfox-net-isos
        aws_region: sa-east-1  # Corrected indentation