---
name: "Build Ublue Hyprland"
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  fedora:
    name: "Fedora"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "fedora"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  solopasha:
    name: "Solopasha"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "solopasha"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  git:
    name: "Git"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "git"
      version: 40
      virtualization: "no"
    permissions:
      contents: read
      packages: write
      id-token: write

  fedora_virt:
    name: "Fedora Virtualization"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "fedora"
      version: 40
      virtualization: "yes"
    permissions:
      contents: read
      packages: write
      id-token: write

  solopasha_virt:
    name: "Solopasha Virtualization"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "solopasha"
      version: 40
      virtualization: "yes"
    permissions:
      contents: read
      packages: write
      id-token: write

  git_virt:
    name: "Git Virtualization"
    uses: ./.github/workflows/image-and-iso.yml
    with:
      variation: "git"
      version: 40
      virtualization: "yes"
    permissions:
      contents: read
      packages: write
      id-token: write
