name: "Build Ublue Hyprland"
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC every day
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  fedora:
    name: "Fedora"
    uses: ./.github/workflows/build-image.yml
    with:
      hyprland_build: "fedora"
      version: 40
      virtualization: "no"
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write

  solopasha:
    name: "Solopasha"
    uses: ./.github/workflows/build-image.yml
    with:
      hyprland_build: "solopasha"
      version: 40
      virtualization: "no"
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write

  git:
    name: "Git"
    uses: ./.github/workflows/build-image.yml
    with:
      hyprland_build: "git"
      version: 40
      virtualization: "no"
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write