name: Main Workflow

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This step is necessary!

      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yml  # Call the reusable workflow
        with:
          message: "Hello from the reusable workflow!"
