name: Main Workflow

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yml  # Referencing the reusable workflow
        with:
          message: "Hello from the reusable workflow!"
