name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to print"
        required: true
        type: string

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a custom message
        run: echo "${{ inputs.message }}"