name: Build Custom ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 builds (optional)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Optional: cache Flatpak and DNF to speed up builds
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/flatpak
            ~/.cache/dnf
          key: ${{ runner.os }}-flatpak-dnf-cache

      # Generate the list of Flatpak refs WITHOUT openh264 dependency
      - name: Generate Flatpak Refs Without openh264
        id: flatpaks
        run: |
          refs=$(cat <<EOF
app/com.github.tchx84.Flatseal/x86_64/stable
app/org.gnome.Calculator/x86_64/stable
app/org.gnome.Evince/x86_64/stable
app/org.gnome.FileRoller/x86_64/stable
app/org.gnome.Logs/x86_64/stable
app/org.gnome.Loupe/x86_64/stable
app/org.gnome.NautilusPreviewer/x86_64/stable
app/org.gnome.FontManager/x86_64/stable
app/org.gnome.SimpleScan/x86_64/stable
app/org.gnome.TextEditor/x86_64/stable
app/org.mozilla.firefox/x86_64/stable
EOF
          )
          echo "FLATPAKS<<EOF" >> $GITHUB_ENV
          echo "$refs" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Optional: Debug the list
      - name: Debug Flatpak Refs
        run: echo "${{ env.FLATPAKS }}"

      # Build the custom ISO
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.3.0
        with:
          image_name: "my-custom-iso"
          image_tag: "latest"
          iso_name: "CustomImage"
          arch: "x86_64"
          variant: "gnome"
          enable_flatpak_dependencies: true
          flatpak_remote_name: "flathub"
          flatpak_remote_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
          flatpak_remote_refs: "${{ env.FLATPAKS }}"
