name: Build Custom ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Flatpak Refs
        id: setup-flatpaks
        run: |
          echo "flatpak_refs<<EOF" >> $GITHUB_OUTPUT
          cat <<EOL >> $GITHUB_OUTPUT
app/com.github.tchx84.Flatseal/x86_64/stable
app/org.gnome.Calculator/x86_64/stable
app/org.gnome.Evince/x86_64/stable
app/org.gnome.FileRoller/x86_64/stable
app/org.gnome.Logs/x86_64/stable
app/org.gnome.Loupe/x86_64/stable
app/org.gnome.NautilusPreviewer/x86_64/stable
app/org.gnome.FontManager/x86_64/stable
app/org.gnome.SimpleScan/x86_64/stable
app/org.gnome.TextEditor/x86_64/stable
app/org.mozilla.firefox/x86_64/stable
EOL
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug Flatpak Refs
        run: echo "${{ steps.setup-flatpaks.outputs.flatpak_refs }}"

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.3.0
        with:
          image_name: "my-custom-iso"
          image_tag: "latest"
          iso_name: "CustomImage"
          arch: "x86_64"
          variant: "gnome"
          enable_flatpak_dependencies: true
          flatpak_remote_name: "flathub"
          flatpak_remote_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
          flatpak_remote_refs: "${{ steps.setup-flatpaks.outputs.flatpak_refs }}"
