---
name: Installer ISO
on: 
  workflow_call:
    inputs:
      fedora_version:
        description: "The Fedora release version: 39, 40, 41 etc"
        type: string
        required: true
jobs:
  iso:
    name: Build Installer ISO
    runs-on: ubuntu-latest
    outputs:
      iso_name: ${{ steps.build_iso.outputs.iso_name }}
      checksum: ${{ steps.build_iso.outputs.iso_name }}-CHECKSUM
    strategy:
      fail-fast: false
      matrix:
        fedora_version:
        - ${{ inputs.fedora_version }}
        hyprland_build:
        - fedora
        - solopasha
        - git
    env:
      ARCH: "x86_64"
      IMAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.hyprland_build }}
      IMAGE_REPO: "ghcr.io/cjuniorfox"
      IMAGE_TAG: ${{ matrix.fedora_version }}
      VARIANT: "base-main"
      VERSION: ${{ matrix.fedora_version }}

    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4 # Updated to latest stable version
  
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.2
        id: build_iso
        with:
          arch: ${{ env.ARCH }}
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ${{ env.IMAGE_REPO }}
          image_tag: ${{ env.IMAGE_TAG }}
          version: ${{ env.VERSION }}
          variant: ${{ env.VARIANT }}
          iso_name: ${{ env.IMAGE_NAME }}-${{ env.ARCH }}-${{ env.IMAGE_TAG }}.iso
          secure_boot_key_url: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          enrollment_password: 'ublue-os'
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"
          flatpak_remote_refs: "com.github.tchx84.Flatseal \
            org.gnome.Calculator \
            org.gnome.Evince \
            org.gnome.FileRoller \
            org.gnome.FontManager \
            org.gnome.Loupe \
            org.gnome.TextEditor \
            org.mozilla.firefox \
            org.freedesktop.Platform.openh264/x86_64/2.4.1 \
            org.freedesktop.Platform.ffmpeg-full/x86_64/24.08"
  
      - name: Move ISOs to Upload Directory
        id: upload_directory
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          mkdir ${ISO_UPLOAD_DIR}
          mv ${{ steps.build_iso.outputs.iso_path }}/${{ steps.build_iso.outputs.iso_name }} ${ISO_UPLOAD_DIR}
          mv ${{ steps.build_iso.outputs.iso_path }}/${{ steps.build_iso.outputs.iso_name }}-CHECKSUM ${ISO_UPLOAD_DIR}
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> $GITHUB_OUTPUT
            
      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_iso.outputs.iso_name }}
          path: ${{ steps.upload_directory.outputs.iso-upload-dir }}
          if-no-files-found: error
          retention-days: 1 # Updated to a valid retention period

      - name: Upload to S3
        id: upload_to_s3
        uses: './.github/workflows/upload-iso-to-s3.yml'
        with:
          s3_bucket: juniorfox-net-isos
          aws_region: sa-east-1
          iso_name: ${{ steps.build_iso.outputs.iso_name }}
          checksum: ${{ steps.build_iso.outputs.iso_name }}-CHECKSUM