---
name: "Build ISO for Ublue Hyprland"
on:
  schedule:
    - cron: '05 12 * * 1/2'  # 12:05am UTC every two weeks on Monday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  version39:
    name: "Fedora Hyprland ISO 39"
    uses: "./.github/workflows/build-iso-variants.yml"
    with:
      version: 39
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: read
      packages: write
      id-token: write
  
  version40:
    name: "Fedora Hyprland ISO 40"
    uses: "./.github/workflows/build-iso-variants.yml"
    with:
      version: 40
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: read
      packages: write
      id-token: write

  version41:
    name: "Fedora Hyprland ISO 41"
    if: false
    uses: "./.github/workflows/build-iso-variants.yml"
    with:
      version: 41
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: read
      packages: write
      id-token: write