---
name: upload-iso-to-s3
on:
  workflow_call:
    inputs:
      s3_bucket:
        type: string
      aws_region:
        type: string
      iso_name:
        type: string
      checksum:
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEU:
        required: true

jobs:
  upload_iso_to_s3:
    name: Publish ISO Installer
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{inputs.s3_bucket}}
      AWS_REGION: ${{inputs.aws_region}}
      ISO_NAME: ${{ inputs.iso_name }}
      CHECKSUM: ${{ inputs.checksum }}

    steps:
      - name: Download ISO Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ISO_NAME}}
          path: ./iso-output
          
      - name: Upload ISO to S3
        id: upload
        run: |
          echo "uploading ${{ env.ISO_NAME }}"
          aws s3 cp "./iso-output/${{ env.ISO_NAME }}" "s3://${{ env.S3_BUCKET }}/${{ env.ISO_NAME }}"
          aws s3 cp "./iso-output/${{ env.CHECKSUM }}" "s3://${{ env.S3_BUCKET }}/${{ env.CHECKSUM }}"

      - name: Make ISO public
        id: make_public
        run : |
          aws s3api put-object-acl --bucket ${{ env.S3_BUCKET }} --key "${{ env.ISO_NAME }}" --acl public-read
          aws s3api put-object-acl --bucket ${{ env.S3_BUCKET }} --key "${{ env.CHECKSUM }}" --acl public-read
        
      - name: Output ISO url
        id: upload_iso_url
        run : |
          echo "https://${{ env.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ISO_NAME }}"
          echo "https://${{ env.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.CHECKSUM }}"