---
  name: upload-iso-to-s3
  on:
    workflow_call:
  jobs:            
    upload_iso_to_s3:
      name: Publish ISO Installer
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: juniorfox-net-isos
        AWS_REGION: sa-east-1
        ISO_NAME: ${{ needs.build_iso.outputs.iso_name }}
        CHECKSUM: ${{ needs.build_iso.outputs.checksum }}
      
      steps:
        - name: Download ISO Artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ env.ISO_NAME}}
            path: ./iso-output
        
        - name: Upload ISO to S3
          id: upload
          run: |
            echo "uploading ${{ env.ISO_NAME }}"
            aws s3 cp "./iso-output/${{ env.ISO_NAME }}" "s3://${{ env.S3_BUCKET }}/${{ env.ISO_NAME }}"
            aws s3 cp "./iso-output/${{ env.CHECKSUM }}" "s3://${{ env.S3_BUCKET }}/${{ env.CHECKSUM }}"
        
        - name: Make ISO public
          id: make_public
          run : |
            aws s3api put-object-acl --bucket ${{ env.S3_BUCKET }} --key "${{ env.ISO_NAME }}" --acl public-read
            aws s3api put-object-acl --bucket ${{ env.S3_BUCKET }} --key "${{ env.CHECKSUM }}" --acl public-read
        
        - name: Output ISO url
          id: upload_iso_url
          run : |
            echo "https://${{ env.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ISO_NAME }}"
            echo "https://${{ env.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ env.CHECKSUM }}"